# Hermitian Matrices, Unitary Matrices and Tensor Product


# Understanding Complex Hermitian and Unitary Matrices

This tutorial delves into two pivotal concepts in quantum computing and linear algebra: complex Hermitian and Unitary matrices. Both play critical roles in quantum mechanics and quantum computing, underpinning the behavior of quantum systems and the operations performed on them.

## Objectives
- Define and explore the properties of complex Hermitian matrices.
- Understand and implement complex Unitary matrices in Python.
- Highlight their significance and applications in quantum computing.

Prepare to enhance your mathematical toolkit with these foundational concepts, illustrated with Python examples for a hands-on learning experience.



## Complex Hermitian Matrices

A Hermitian matrix, or self-adjoint matrix, is a square matrix that is equal to its own conjugate transpose. This property makes it a natural representation of observable quantities in quantum mechanics.

### Properties
- The eigenvalues of a Hermitian matrix are always real.
- The eigenvectors of a Hermitian matrix corresponding to different eigenvalues are orthogonal.
- Hermitian matrices are extensively used in quantum mechanics to describe physical observables.

### Python Example: Defining a Hermitian Matrix


In [ ]:

import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[2+0j, 2-1j], [2+1j, 3+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix


(True,
 array([[2.+0.j, 2.-1.j],
        [2.+1.j, 3.+0.j]]))


## Complex Unitary Matrices

A Unitary matrix is a square matrix whose conjugate transpose is also its inverse. Unitary matrices preserve the inner product, making them essential for describing quantum gates and evolution in quantum computing.

### Properties
- Preserves the norm of vectors, hence preserving quantum states during transformations.
- The determinant of a Unitary matrix has an absolute value of 1.
- Used to represent reversible quantum operations and time evolution in quantum systems.

### Python Example: Defining a Unitary Matrix


In [ ]:

# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix


(True,
 array([[ 0.70710678+0.j        ,  0.70710678+0.j        ],
        [ 0.        +0.70710678j, -0.        -0.70710678j]]))

# Tensor product


## Tensor Product for Complex Vectors

The tensor product of two complex vectors creates a new vector in a higher-dimensional space, allowing us to combine quantum states in quantum computing.

### Example


In [ ]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5+6j, 7+8j])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v


array([ -7.+16.j,  -9.+22.j,  -9.+38.j, -11.+52.j])


## Tensor Product for Complex Matrices

The tensor product for matrices combines individual matrices into a larger matrix, crucial for representing multiple qubit systems in quantum computing.

### Example


In [ ]:

# Define two complex matrices for the tensor product
M1 = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
M2 = np.array([[9+10j, 11+12j], [13+14j, 15+16j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


array([[-11. +28.j, -13. +34.j, -13. +66.j, -15. +80.j],
       [-15. +40.j, -17. +46.j, -17. +94.j, -19.+108.j],
       [-15.+104.j, -17.+126.j, -17.+142.j, -19.+172.j],
       [-19.+148.j, -21.+170.j, -21.+202.j, -23.+232.j]])

# Exercises on Complex Vector and Matrix Operations

This set of exercises is designed to test your understanding of various concepts related to complex vector and matrix operations, which are foundational in quantum computing. Each exercise presents a concrete case for you to apply what you've learned about Hermitian matrices, Unitary matrices, and tensor products.

NOTE: VERIFY YOUR COMPUTATIONS IN PAPER AND IN THE COMPUTER.

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.

## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

## Exercise 6: Composing quantum systems

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)



# Ejercicio 1: Verificar si una matriz es Hermitiana y calcular autovalores

In [1]:
import numpy as np

# Definimos la matriz H
H = np.array([[3, 2 - 1j],
              [2 + 1j, 1]])

# Verificar si es Hermitiana
is_hermitian = np.allclose(H, H.conj().T)

# Calcular valores propios
eigenvalues, eigenvectors = np.linalg.eig(H)

print("¿Es Hermitiana?", is_hermitian)
print("Valores propios:", eigenvalues)
print("Vectores propios:\n", eigenvectors)


¿Es Hermitiana? True
Valores propios: [ 4.44948974+6.70989255e-17j -0.44948974-1.15877743e-17j]
Vectores propios:
 [[ 0.83912106+0.j         -0.48651894+0.24325947j]
 [ 0.48651894+0.24325947j  0.83912106+0.j        ]]


# Ejercicio 2: Verificar si una matriz es Unitaria y calcular U * U†

In [ ]:
import numpy as np

# Definimos la matriz U
U = (1/np.sqrt(2)) * np.array([[1, 1],
                               [1j, -1j]])

# Verificar si es Unitaria
is_unitary = np.allclose(U @ U.conj().T, np.eye(2))

print("¿Es Unitaria?", is_unitary)
print("U * U† =\n", U @ U.conj().T)


¿Es Unitaria? True
U * U† =
 [[1.+0.00000000e+00j 0.+2.23711432e-17j]
 [0.-2.23711432e-17j 1.+0.00000000e+00j]]


# Ejercicio 3: Producto tensorial de dos vectores complejos

In [2]:
import numpy as np

# Vectores complejos
v = np.array([1 + 1j, 2 - 1j])
w = np.array([1 - 2j, 3])

# Producto tensorial
tensor_product_v = np.kron(v, w)

print("Producto tensorial v ⊗ w =\n", tensor_product_v)


Producto tensorial v ⊗ w =
 [3.-1.j 3.+3.j 0.-5.j 6.-3.j]


# Ejercicio 4: Producto tensorial de dos matrices complejas

In [3]:
import numpy as np

# Matrices
M1 = np.array([[0, 1],
               [1, 0]])

M2 = np.array([[1j, 0],
               [0, -1j]])

# Producto tensorial
tensor_product_m = np.kron(M1, M2)

print("Producto tensorial M1 ⊗ M2 =\n", tensor_product_m)


Producto tensorial M1 ⊗ M2 =
 [[0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.-0.j]]


# Ejercicio 5: Modelo del interferómetro de Mach-Zehnder

In [4]:
import numpy as np

# Matriz Hadamard
H = (1/np.sqrt(2)) * np.array([[1, 1],
                               [1, -1]])

# Matriz de fase
P = np.array([[1, 0],
              [0, np.exp(1j * np.pi/2)]])

# Estado inicial
psi0 = np.array([1, 0])

# Aplicar operaciones: H -> P -> H
psi1 = H @ psi0
psi2 = P @ psi1
psi3 = H @ psi2

print("Estado final Mach-Zehnder =", psi3)


Estado final Mach-Zehnder = [0.5+0.5j 0.5-0.5j]


# Ejercicio 6: Composición de sistemas cuánticos con Uf

In [5]:
import numpy as np

# Hadamard (H)
H = (1/np.sqrt(2)) * np.array([[1, 1],
                               [1, -1]])

# Uf (ejemplo dado en muchos problemas de computación cuántica)
Uf = np.array([[1, 0, 0, 0],
               [0, 0, 0, 1],
               [0, 0, 1, 0],
               [0, 1, 0, 0]])

# Estado inicial |0⟩|1⟩
psi0 = np.array([0, 1, 0, 0])

# H en el primer qubit => aplicamos H ⊗ I
H1 = np.kron(H, np.eye(2))
psi1 = H1 @ psi0

# Aplicar Uf
psi2 = Uf @ psi1

# Medir estado final
print("Estado final del sistema =", psi2)


Estado final del sistema = [0.         0.70710678 0.         0.70710678]
